name: Testnet check

on:
  pull_request:
    branches:
      - testnet-check

jobs:
  run-testnet-check:
    runs-on: ubuntu-latest
    steps:
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: retrieve pr code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker compose
        run: |
          docker-compose up -d
          docker container rename baby_node_1 baby-node-1
          docker exec baby-node-1 babyd version
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: check address balances
        run: |
          chmod a+x ./homework/check-balances.sh
          bash homework/check-balances.sh
      - name: check chain id
        run: |
          chmod a+x ./homework/check-chain-id.sh
          bash homework/check-chain-id.sh